import { Roboto } from "next/font/google";

import Navbar from "./auth/Navbar";

import "./globals.css";

const roboto = Roboto({
  subsets: ["latin"],
  weight: ["400", "700"],
  variable: "--font-roboto",
});

export const metadata = {
  title: "PostIt",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`mx-4 md:mx-48 xl:md-96 ${roboto.variable} bg-gray-200`}>
        <Navbar />
        {children}
      </body>
    </html>
  );
}
